### ISSUE TITLE
Minor issue : why a project with static name (airspy)

### ISSUE THREAD

**Issue by F5OEO** [BritishAmateurTelevisionClub/eshail-ghy-wb-fft-airspy#3]
Want to fork it to port this excellent project to an other SDR (PlutoSDR indeed), but project name still remain airspy. Any idea to not be confusing ?

**Comment by philcrump** [comment]
Hi Evariste, there's nothing to stop you renaming your fork of the repository. I'd like to keep this version as airspy-only as it reduces the work to maintain the websdr. Phil

**Comment by F5OEO** [comment]
Makes sense. Thanks Phil.
